shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from .views import ProductDetailView, CategoryDetailView, IndexView, CartView, AddProductToCartView, ChangeQuantityView, DeleteFromCart

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'), 
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'), 
    path('add_to_cart/<str:ct_model>/<str:slug>', AddProductToCartView.as_view(), name='add_to_cart'),
    path('change_quantity/<str:ct_model>/<str:slug>', ChangeQuantityView.as_view(), name='change_quantity'),  
    path('delete_from_cart/<str:ct_model>/<str:slug>', DeleteFromCart.as_view(), name='delete_from_cart'),  
]

web/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils import timezone
from django.urls import reverse

User = get_user_model()

def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})





class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count'
    }
    
    def get_queryset(self):
        return super().get_queryset()

    def get_models_for_count(self, *model_names):
        return [models.Count(model_name) for model_name in model_names]

    def get_categories_for_left_sidebar(self):
        models = self.get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data

        
class Category(models.Model):
    
    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (800, 800)
    MAX_IMAGE_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=250, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(verbose_name='Изображение')

    def __str__(self):
        return self.title

    def get_url(self):
        return get_product_url(self, 'product_detail')

    def get_model_name(self):
        return self.__class__.__name__.lower()

class Notebook(Product):

    class Meta:
        verbose_name = 'ноутбук' 
        verbose_name_plural = 'Ноутбуки'

    diagonal = models.CharField(max_length=250, verbose_name='Диагональ')
    display_type = models.CharField(max_length=250, verbose_name='Тип дисплея')
    ram = models.CharField(max_length=250, verbose_name='Оперативная память')
    processor_freq = models.CharField(max_length=250, verbose_name='Частота процессора')
    video = models.CharField(max_length=250, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=250, verbose_name='Время работы аккумулятора')
    os = models.CharField(max_length=250, verbose_name='Операционная система')


class Smartphone(Product):
    
    class Meta:
        verbose_name = 'смартфон' 
        verbose_name_plural = 'Смартфоны'
    
    diagonal = models.CharField(max_length=250, verbose_name='Диагональ')
    display_type = models.CharField(max_length=250, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=250, verbose_name='Разрешение экрана')
    
    ram = models.CharField(max_length=250, verbose_name='Оперативная память')
    accum_volume = models.CharField(max_length=250, verbose_name='Объем батареи')

    sd = models.BooleanField(default=False, verbose_name='SD карта')
    sd_volume = models.CharField(max_length=250, verbose_name='Максимальный объём sd карты', null=True, blank=True)

    main_cam = models.CharField(max_length=250, verbose_name='Задняя камера')
    frontal_cam = models.CharField(max_length=250, verbose_name='Фронтальная камера')


class Cart(models.Model):

    class Meta:
        verbose_name = 'корзина'
        verbose_name_plural = 'Корзины'

    owner = models.ForeignKey('Customer', verbose_name='Владелец', on_delete=models.CASCADE, null=True, blank=True)
    products = models.ManyToManyField('CartProduct', blank=True, related_name='products')
    total_products = models.PositiveIntegerField(default=0)
    
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)
    
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена', default=0)

    
    def __str__(self):
        return 'Корзина №' + str(self.id)


class CartProduct(models.Model):

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'Продукты корзин'

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    quantity = models.PositiveIntegerField(default=1)

    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена', default=0)

    def __str__(self):
        return 'Продукт %s из корзины %d' % (self.content_object.title, self.cart.id)

    def save(self, *args, **kwargs):
        self.final_price = self.quantity * self.content_object.price
        return super().save(*args, **kwargs)    


class Customer(models.Model):
    
    class Meta:
        verbose_name = 'покупатель'
        verbose_name_plural = 'Покупатели'

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=250, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы пользователя', related_name='orders', blank=True)

    def __str__(self):
        return 'Покупатель %s %s' % (self.user.first_name, self.user.last_name)


class Order(models.Model):

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'Заказы'

    STATUS_DEFAULT = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'ready'
    STATUS_COMPLETED = 'completed'

    STATUS_CHOICES = (
        (STATUS_DEFAULT, 'Новый'),
        (STATUS_IN_PROGRESS, 'В обработке'), 
        (STATUS_READY, 'Готов'),
        (STATUS_COMPLETED, 'Выполнен'),
    )

    DELIVERY_TYPE_DEFAULT = 'self'
    DELIVERY_TYPE_DELIVERY = 'delivery'

    DELIVERY_TYPE_CHOICES = (
        (DELIVERY_TYPE_DEFAULT, 'Самовывоз'), 
        (DELIVERY_TYPE_DELIVERY, 'Доставка'), 
    )

    customer = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    
    first_name = models.CharField(max_length=30, verbose_name='Имя покупателя')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия покупателя')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)

    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=100, verbose_name='Статус заказа', choices=STATUS_CHOICES, default=STATUS_DEFAULT)
    delivery_type = models.CharField(max_length=100, verbose_name='Тип доставки', choices=DELIVERY_TYPE_CHOICES, default=DELIVERY_TYPE_DEFAULT)

    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    order_date = models.DateField(default=timezone.now, verbose_name='Дата получения заказа')

    def __str__(self):
        return 'Заказ №%d' % (self.id)


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = list()

        ct_models = ContentType.objects.filter(model__in=args)

        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)

        if with_respect_to and with_respect_to in args:
            ct_models = ContentType.objects.filter(model=with_respect_to)
            if ct_models.exists():
                products = sorted(
                    products, 
                    key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                )

        return products


class LatestProducts:
    objects = LatestProductsManager()

web/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function($) {
        $('#id_sd').on('click', () => {
            if ($('#id_sd').prop('checked') == true) {
                $('#id_sd_volume').prop('readonly', false)
                $('#id_sd_volume').css('background', '#121212')
            } else {
                $('#id_sd_volume').prop('readonly', true)
                $('#id_sd_volume').css('background', 'black')
            }
            $('#id_sd_volume').val('')
        })
    }) (django.jQuery)
</script>
{% endblock %}

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Shop Homepage - Start Bootstrap Template</title>
        
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'cart' %}">
                                Корзина
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <h1 class="my-4">Shop Name</h1>
                    <div class="list-group">
                        {% for category in categories %}
                            <a class="list-group-item" href="{{ category.url }}">{{ category.name }} ({{ category.count }})</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-9">
                    {% block content %}
                    <div class="carousel slide my-4" id="carouselExampleIndicators" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li class="active" data-target="#carouselExampleIndicators" data-slide-to="0"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active"><img class="d-block img-fluid" src="/media/promo.jpg" alt="First slide" /></div>
                            <div class="carousel-item"><img class="d-block img-fluid" src="/media/promo.jpg" alt="Second slide" /></div>
                            <div class="carousel-item"><img class="d-block img-fluid" src="/media/promo.jpg" alt="Third slide" /></div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-4 col-md-6 mb-4">
                                <div class="card h-100">
                                    <a href="{{ product.get_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt="..."></a>
                                    <div class="card-body">
                                        <h4 class="card-title"><a href="{{ product.get_url }}">{{ product.title }}</a></h4>
                                        <h5>{{ product.price }} тнг.</h5>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% endblock content %}
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

web/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" style="margin-top: 20px;">
                <strong>{{message}}</strong>
                <button class="close" type="button" data-dismiss="alert" role="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    {% if not cart.products.count %}
        <h3 class="text-center mt-5 mb-5">Ваша корзина пуста!</h3>
    {% else %}
        <h3 class="text-center mt-5 mb-5">Корзина</h3>

        <table class="table" style="margin-bottom: 20px;">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Изображение</th>
                    <th scope="col">Цена за ед. товара</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Общая цена</th>
                </tr>
            </thead>
            <tbody>
                {% for product in cart.products.all %}
                    <tr>
                        <th scope="row">{{ product.content_object.title }}</th>
                        <td class="w-25">
                            <img class="img-fluid" src="{{ product.content_object.image.url }}" alt="">
                        </td>
                        <td>{{ product.content_object.price }} тнг.</td>
                        <td>
                            <form action="{% url 'change_quantity' ct_model=product.content_object.get_model_name slug=product.content_object.slug %}" method="POST">
                                {% csrf_token %}
                                <input type="number" class="form-control" name="quantity" style="max-width: 70px;" min="1" value="{{ product.quantity }}">
                                <input type="submit" class="btn btn-primary" value="Изменить">
                            </form>
                        </td>
                        <td>{{ product.final_price }} тнг.</td>
                        <td>
                            <a href="{% url 'delete_from_cart' ct_model=product.content_object.get_model_name slug=product.content_object.slug %}">
                                <button class="btn btn-danger">Удалить</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2"></td>
                    <th scope="row">Итого:</th>
                    <td>{{ cart.total_products }}</td>
                    <td>{{ cart.final_price }} тнг.</td>
                </tr>
            </tbody>
        </table>
    {% endif %}

{% endblock %}

web/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
            <li class="breadcrumb-item"aria-current="page">{{ category.name }}</li>
        </ol>
    </nav>
    <div class="row">
        {% for product in category_products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="{{ product.get_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt="..."></a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="{{ product.get_url }}">{{ product.title }}</a></h4>
                        <h5>{{ product.price }} тнг.</h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

web/templates/notebook_specification.html
<table class="table">
<tbody>
    <tr>
        <td>Диагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплея</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Оперативная память</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Частота процессора</td>
        <td>{{ product.processor_freq }}</td>
    </tr>
    <tr>
        <td>Видеокарта</td>
        <td>{{ product.video }}</td>
    </tr>
    <tr>
        <td>Время работы аккумулятора</td>
        <td>{{ product.time_without_charge }}</td>
    </tr>
    <tr>
        <td>Операционная система</td>
        <td>{{ product.os }}</td>
    </tr>
</tbody>
</table>
  

web/templates/notebook_specifications.html
<table class="table">
    <tbody>
        <tr>
            <td>Диагональ</td>
            <td>{{ product.diagonal }}</td>
        </tr>
        <tr>
            <td>Тип дисплея</td>
            <td>{{ product.display_type }}</td>
        </tr>
        <tr>
            <td>Оперативная память</td>
            <td>{{ product.ram }}</td>
        </tr>
        <tr>
            <td>Частота процессора</td>
            <td>{{ product.processor_freq }}</td>
        </tr>
        <tr>
            <td>Видеокарта</td>
            <td>{{ product.video }}</td>
        </tr>
        <tr>
            <td>Время работы аккумулятора</td>
            <td>{{ product.time_without_charge }}</td>
        </tr>
        <tr>
            <td>Операционная система</td>
            <td>{{ product.os }}</td>
        </tr>
    </tbody>
</table>

web/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{ product.category.get_url }}">{{ product.category.name }}</a></li>
            <li class="breadcrumb-item"aria-current="page">{{ product.title }}</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-4">
            <img src="{{ product.image.url }}" alt="" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3>{{ product.title }}</h3>
            <p>Цена: <span>{{ product.price }}</span></p>
            <p>Описание: {{ product.description }}</p>
            <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}"><button class="btn btn-danger">Добавить в корзину</button></a>
        </div>
        
        <p class="mt-4">Характеристики:</p>
        
        {{ product | product_specifications }}
    
    </div>
{% endblock content %}

web/templates/smartphone_specification.html
<table class="table">
    <tbody>
        <tr>
            <td>Диагональ</td>
            <td>{{ product.diagonal }}</td>
        </tr>
        <tr>
            <td>Тип дисплея</td>
            <td>{{ product.display_type }}</td>
        </tr>
        <tr>
            <td>Разрешение экрана</td>
            <td>{{ product.resolution }}</td>
        </tr>
        <tr>
            <td>Оперативная память</td>
            <td>{{ product.ram }}</td>
        </tr>
        <tr>
            <td>Объем батареи</td>
            <td>{{ product.accum_volume }}</td>
        </tr>
        <tr>
            <td>SD карта</td>
            <td>{{ product.sd_volume }}</td>
        </tr>
        <tr>
            <td>Задняя камера</td>
            <td>{{ product.main_cam }}</td>
        </tr>
        <tr>
            <td>Фронтальная камера</td>
            <td>{{ product.frontal_cam }}</td>
        </tr>
    </tbody>
    </table>
      

web/templates/smartphone_specifications.html
<table class="table">
    <tbody>
        <tr>
            <td>Диагональ</td>
            <td>{{ product.diagonal }}</td>
        </tr>
        <tr>
            <td>Тип дисплея</td>
            <td>{{ product.display_type }}</td>
        </tr>
        <tr>
            <td>Разрешение экрана</td>
            <td>{{ product.resolution }}</td>
        </tr>
        <tr>
            <td>Оперативная память</td>
            <td>{{ product.ram }}</td>
        </tr>
        <tr>
            <td>Объем батареи</td>
            <td>{{ product.accum_volume }}</td>
        </tr>
        {% if product.sd %}
        <tr>
            <td>Максимальный объем SD карты</td>
            <td>{{ product.sd_volume }}</td>
        </tr>
        {% endif %}
        <tr>
            <td>Задняя камера</td>
            <td>{{ product.main_cam }}</td>
        </tr>
        <tr>
            <td>Передняя камера</td>
            <td>{{ product.frontal_cam }}</td>
        </tr>
    </tbody>
</table>